races = [
  {
    races: [
      {
        "Grand Prix": "Bahrain",
        Date: "20 Mar 2022",
        Winner: "Charles Leclerc",
        Car: "Ferrari",
        Laps: 57,
        Time: "1:37:33.584",
      },
      {
        "Grand Prix": "Saudi Arabia",
        Date: "27 Mar 2022",
        Winner: "Max Verstappen",
        Car: "Red Bull Racing RBPT",
        Laps: 50,
        Time: "1:24:19.293",
      },
      {
        "Grand Prix": "Australia",
        Date: "10 Apr 2022",
        Winner: "Charles Leclerc",
        Car: "Ferrari",
        Laps: 58,
        Time: "1:27:46.548",
      },
      {
        "Grand Prix": "Emilia Romagna",
        Date: "24 Apr 2022",
        Winner: "Max Verstappen",
        Car: "Red Bull Racing RBPT",
        Laps: 63,
        Time: "1:32:07.986",
      },
      {
        "Grand Prix": "Miami",
        Date: "08 May 2022",
        Winner: "Max Verstappen",
        Car: "Red Bull Racing RBPT",
        Laps: 57,
        Time: "1:34:24.258",
      },
      {
        "Grand Prix": "Spain",
        Date: "22 May 2022",
        Winner: "Max Verstappen",
        Car: "Red Bull Racing RBPT",
        Laps: 66,
        Time: "1:37:20.475",
      },
      {
        "Grand Prix": "Monaco",
        Date: "29 May 2022",
        Winner: "Sergio Perez",
        Car: "Red Bull Racing RBPT",
        Laps: 64,
        Time: "1:56:30.265",
      },
      {
        "Grand Prix": "Azerbaijan",
        Date: "12 Jun 2022",
        Winner: "Max Verstappen",
        Car: "Red Bull Racing RBPT",
        Laps: 51,
        Time: "1:34:05.941",
      },
      {
        "Grand Prix": "Canada",
        Date: "19 Jun 2022",
        Winner: "Max Verstappen",
        Car: "Red Bull Racing RBPT",
        Laps: 70,
        Time: "1:36:21.757",
      },
      {
        "Grand Prix": "Great Britain",
        Date: "03 Jul 2022",
        Winner: "Carlos Sainz",
        Car: "Ferrari",
        Laps: 52,
        Time: "2:17:50.311",
      },
      {
        "Grand Prix": "Austria",
        Date: "10 Jul 2022",
        Winner: "Charles Leclerc",
        Car: "Ferrari",
        Laps: 71,
        Time: "1:24:24.312",
      },
    ],
  },
];
forteam = {
  2022: [
    {
      Pos: 1,
      Team: "Red Bull Racing RBPT",
      PTS: 759,
    },
    {
      Pos: 2,
      Team: "Ferrari",
      PTS: 554,
    },
    {
      Pos: 3,
      Team: "Mercedes",
      PTS: 515,
    },
    {
      Pos: 4,
      Team: "Alpine Renault",
      PTS: 173,
    },
    {
      Pos: 5,
      Team: "McLaren Mercedes",
      PTS: 159,
    },
    {
      Pos: 6,
      Team: "Alfa Romeo Ferrari",
      PTS: 55,
    },
    {
      Pos: 7,
      Team: "Aston Martin Aramco Mercedes",
      PTS: 55,
    },
    {
      Pos: 8,
      Team: "Haas Ferrari",
      PTS: 37,
    },
    {
      Pos: 9,
      Team: "AlphaTauri RBPT",
      PTS: 35,
    },
    {
      Pos: 10,
      Team: "Williams Mercedes",
      PTS: 8,
    },
  ],
  2023: [
    {
      Pos: "1",
      Team: "Red Bull Racing Honda RBPT",
      PTS: 321,
    },
    {
      Pos: "2",
      Team: "Mercedes",
      PTS: 167,
    },
    {
      Pos: "3",
      Team: "Aston Martin Aramco Mercedes",
      PTS: 154,
    },
    {
      Pos: "4",
      Team: "Ferrari",
      PTS: 122,
    },
    {
      Pos: "5",
      Team: "Alpine Renault",
      PTS: 44,
    },
    {
      Pos: "6",
      Team: "McLaren Mercedes",
      PTS: 17,
    },
    {
      Pos: "7",
      Team: "Alfa Romeo Ferrari",
      PTS: 9,
    },
    {
      Pos: "8",
      Team: "Haas Ferrari",
      PTS: 8,
    },
    {
      Pos: "9",
      Team: "Williams Mercedes",
      PTS: 7,
    },
    {
      Pos: "10",
      Team: "AlphaTauri Honda RBPT",
      PTS: 2,
    },
  ],
};
forEachTeamIn2023 = {
  "Alfa Romeo Ferrari": [
    {
      "Grand Prix": "Bahrain",
      Date: "05 Mar 2023",
      PTS: 4,
    },
    {
      "Grand Prix": "Saudi Arabia",
      Date: "19 Mar 2023",
      PTS: 0,
    },
    {
      "Grand Prix": "Australia",
      Date: "02 Apr 2023",
      PTS: 2,
    },
    {
      "Grand Prix": "Azerbaijan",
      Date: "30 Apr 2023",
      PTS: 0,
    },
    {
      "Grand Prix": "Miami",
      Date: "07 May 2023",
      PTS: 0,
    },
    {
      "Grand Prix": "Monaco",
      Date: "28 May 2023",
      PTS: 0,
    },
    {
      "Grand Prix": "Spain",
      Date: "04 Jun 2023",
      PTS: 2,
    },
    {
      "Grand Prix": "Canada",
      Date: "18 Jun 2023",
      PTS: 1,
    },
  ],
  "AlphaTauri Honda RBPT": [
    {
      "Grand Prix": "Bahrain",
      Date: "05 Mar 2023",
      PTS: 0,
    },
    {
      "Grand Prix": "Saudi Arabia",
      Date: "19 Mar 2023",
      PTS: 0,
    },
    {
      "Grand Prix": "Australia",
      Date: "02 Apr 2023",
      PTS: 1,
    },
    {
      "Grand Prix": "Azerbaijan",
      Date: "30 Apr 2023",
      PTS: 1,
    },
    {
      "Grand Prix": "Miami",
      Date: "07 May 2023",
      PTS: 0,
    },
    {
      "Grand Prix": "Monaco",
      Date: "28 May 2023",
      PTS: 0,
    },
    {
      "Grand Prix": "Spain",
      Date: "04 Jun 2023",
      PTS: 0,
    },
    {
      "Grand Prix": "Canada",
      Date: "18 Jun 2023",
      PTS: 0,
    },
  ],
};
forEachDriver = {
  2023: {
    "Max Verstappen": [
      {
        "Grand Prix": "Bahrain",
        Date: "05 Mar 2023",
        Car: "Red Bull Racing Honda RBPT",
        "Race Position": "1",
        PTS: 25,
      },
      {
        "Grand Prix": "Saudi Arabia",
        Date: "19 Mar 2023",
        Car: "Red Bull Racing Honda RBPT",
        "Race Position": "2",
        PTS: 19,
      },
      {
        "Grand Prix": "Australia",
        Date: "02 Apr 2023",
        Car: "Red Bull Racing Honda RBPT",
        "Race Position": "1",
        PTS: 25,
      },
      {
        "Grand Prix": "Azerbaijan",
        Date: "30 Apr 2023",
        Car: "Red Bull Racing Honda RBPT",
        "Race Position": "2",
        PTS: 24,
      },
      {
        "Grand Prix": "Miami",
        Date: "07 May 2023",
        Car: "Red Bull Racing Honda RBPT",
        "Race Position": "1",
        PTS: 26,
      },
      {
        "Grand Prix": "Monaco",
        Date: "28 May 2023",
        Car: "Red Bull Racing Honda RBPT",
        "Race Position": "1",
        PTS: 25,
      },
      {
        "Grand Prix": "Spain",
        Date: "04 Jun 2023",
        Car: "Red Bull Racing Honda RBPT",
        "Race Position": "1",
        PTS: 26,
      },
      {
        "Grand Prix": "Canada",
        Date: "18 Jun 2023",
        Car: "Red Bull Racing Honda RBPT",
        "Race Position": "1",
        PTS: 25,
      },
    ],
    "Alexander Albon": [
      {
        "Grand Prix": "Bahrain",
        Date: "05 Mar 2023",
        Car: "Williams Mercedes",
        "Race Position": "10",
        PTS: 1,
      },
      {
        "Grand Prix": "Saudi Arabia",
        Date: "19 Mar 2023",
        Car: "Williams Mercedes",
        "Race Position": "DNF",
        PTS: 0,
      },
      {
        "Grand Prix": "Australia",
        Date: "02 Apr 2023",
        Car: "Williams Mercedes",
        "Race Position": "DNF",
        PTS: 0,
      },
      {
        "Grand Prix": "Azerbaijan",
        Date: "30 Apr 2023",
        Car: "Williams Mercedes",
        "Race Position": "12",
        PTS: 0,
      },
      {
        "Grand Prix": "Miami",
        Date: "07 May 2023",
        Car: "Williams Mercedes",
        "Race Position": "14",
        PTS: 0,
      },
      {
        "Grand Prix": "Monaco",
        Date: "28 May 2023",
        Car: "Williams Mercedes",
        "Race Position": "14",
        PTS: 0,
      },
      {
        "Grand Prix": "Spain",
        Date: "04 Jun 2023",
        Car: "Williams Mercedes",
        "Race Position": "16",
        PTS: 0,
      },
      {
        "Grand Prix": "Canada",
        Date: "18 Jun 2023",
        Car: "Williams Mercedes",
        "Race Position": "7",
        PTS: 6,
      },
    ],
  },
  2022: {
    "Alexander Albon": [
      {
        "Grand Prix": "Bahrain",
        Date: "05 Mar 2023",
        Car: "Williams Mercedes",
        "Race Position": "10",
        PTS: 1,
      },
      {
        "Grand Prix": "Saudi Arabia",
        Date: "19 Mar 2023",
        Car: "Williams Mercedes",
        "Race Position": "DNF",
        PTS: 0,
      },
      {
        "Grand Prix": "Australia",
        Date: "02 Apr 2023",
        Car: "Williams Mercedes",
        "Race Position": "DNF",
        PTS: 0,
      },
      {
        "Grand Prix": "Azerbaijan",
        Date: "30 Apr 2023",
        Car: "Williams Mercedes",
        "Race Position": "12",
        PTS: 0,
      },
      {
        "Grand Prix": "Miami",
        Date: "07 May 2023",
        Car: "Williams Mercedes",
        "Race Position": "14",
        PTS: 0,
      },
      {
        "Grand Prix": "Monaco",
        Date: "28 May 2023",
        Car: "Williams Mercedes",
        "Race Position": "14",
        PTS: 0,
      },
      {
        "Grand Prix": "Spain",
        Date: "04 Jun 2023",
        Car: "Williams Mercedes",
        "Race Position": "16",
        PTS: 0,
      },
      {
        "Grand Prix": "Canada",
        Date: "18 Jun 2023",
        Car: "Williams Mercedes",
        "Race Position": "7",
        PTS: 6,
      },
    ],
    "": [
      {
        "Grand Prix": "Bahrain",
        Date: "20 Mar 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "DNF",
        PTS: "0",
      },
      {
        "Grand Prix": "Saudi Arabia",
        Date: "27 Mar 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "1",
        PTS: "25",
      },
      {
        "Grand Prix": "Australia",
        Date: "10 Apr 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "DNF",
        PTS: "0",
      },
      {
        "Grand Prix": "Emilia Romagna",
        Date: "24 Apr 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "1",
        PTS: "34",
      },
      {
        "Grand Prix": "Miami",
        Date: "08 May 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "1",
        PTS: "26",
      },
      {
        "Grand Prix": "Spain",
        Date: "22 May 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "1",
        PTS: "25",
      },
      {
        "Grand Prix": "Monaco",
        Date: "29 May 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "3",
        PTS: "15",
      },
      {
        "Grand Prix": "Azerbaijan",
        Date: "12 Jun 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "1",
        PTS: "25",
      },
      {
        "Grand Prix": "Canada",
        Date: "19 Jun 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "1",
        PTS: "25",
      },
      {
        "Grand Prix": "Great Britain",
        Date: "03 Jul 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "7",
        PTS: "6",
      },
      {
        "Grand Prix": "Austria",
        Date: "10 Jul 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "2",
        PTS: "27",
      },
      {
        "Grand Prix": "France",
        Date: "24 Jul 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "1",
        PTS: "25",
      },
      {
        "Grand Prix": "Hungary",
        Date: "31 Jul 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "1",
        PTS: "25",
      },
      {
        "Grand Prix": "Belgium",
        Date: "28 Aug 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "1",
        PTS: "26",
      },
      {
        "Grand Prix": "Netherlands",
        Date: "04 Sep 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "1",
        PTS: "26",
      },
      {
        "Grand Prix": "Italy",
        Date: "11 Sep 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "1",
        PTS: "25",
      },
      {
        "Grand Prix": "Singapore",
        Date: "02 Oct 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "7",
        PTS: "6",
      },
      {
        "Grand Prix": "Japan",
        Date: "09 Oct 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "1",
        PTS: "25",
      },
      {
        "Grand Prix": "United States",
        Date: "23 Oct 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "1",
        PTS: "25",
      },
      {
        "Grand Prix": "Mexico",
        Date: "30 Oct 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "1",
        PTS: "25",
      },
      {
        "Grand Prix": "Brazil",
        Date: "13 Nov 2022",
        Car: "Red Bull Racing RBPT",
        "Race Position": "6",
        PTS: "13",
      },
    ],
  },
};

races = [
  { year: 2023, grandPrix: "Bahrain", date: "05 Mar 2023" },
  { year: 2023, grandPrix: "Saudi Arabia", date: "19 Mar 2023" },
  { year: 2023, grandPrix: "Australia", date: "02 Apr 2023" },
  { year: 2023, grandPrix: "Azerbaijan", date: "30 Apr 2023" },
  { year: 2023, grandPrix: "Miami", date: "07 May 2023" },
  { year: 2023, grandPrix: "Monaco", date: "28 May 2023" },
  { year: 2023, grandPrix: "Spain", date: "04 Jun 2023" },
];
driver = [
  { fullName: "Max Verstappen ", nationality: "NED" },
  { fullName: "Charles Leclerc ", nationality: "MON" },
  { fullName: "Sergio Perez ", nationality: "MEX" },
  { fullName: "George Russell ", nationality: "GBR" },
  { fullName: "Carlos Sainz ", nationality: "ESP" },
  { fullName: "Lewis Hamilton ", nationality: "GBR" },
  { fullName: "Lando Norris ", nationality: "GBR" },
  { fullName: "Esteban Ocon ", nationality: "FRA" },
  { fullName: "Fernando Alonso ", nationality: "ESP" },
  { fullName: "Valtteri Bottas ", nationality: "FIN" },
  { fullName: "Daniel Ricciardo ", nationality: "AUS" },
  { fullName: "Sebastian Vettel ", nationality: "GER" },
  { fullName: "Kevin Magnussen ", nationality: "DEN" },
  { fullName: "Pierre Gasly ", nationality: "FRA" },
  { fullName: "Lance Stroll ", nationality: "CAN" },
  { fullName: "Mick Schumacher ", nationality: "GER" },
  { fullName: "Yuki Tsunoda ", nationality: "JPN" },
  { fullName: "Zhou Guanyu ", nationality: "CHN" },
  { fullName: "Alexander Albon ", nationality: "THA" },
  { fullName: "Nicholas Latifi ", nationality: "CAN" },
  { fullName: "Nyck De Vries ", nationality: "NED" },
];
data = [
  { id: 1, fullName: "Max Verstappen " },
  { id: 2, fullName: "Charles Leclerc " },
  { id: 3, fullName: "Sergio Perez " },
  { id: 4, fullName: "George Russell " },
  { id: 5, fullName: "Carlos Sainz " },
  { id: 6, fullName: "Lewis Hamilton " },
  { id: 7, fullName: "Lando Norris " },
  { id: 8, fullName: "Esteban Ocon " },
  { id: 9, fullName: "Fernando Alonso " },
  { id: 10, fullName: "Valtteri Bottas " },
  { id: 13, fullName: "Kevin Magnussen " },
  { id: 15, fullName: "Lance Stroll " },
  { id: 18, fullName: "Zhou Guanyu " },
  { id: 19, fullName: "Alexander Albon " },
  { id: 21, fullName: "Nyck De Vries " },
  { id: 22, fullName: "Oscar Piastri" },
  { id: 23, fullName: "Pierre Gasly" },
  { id: 24, fullName: "Nico Hulkenberg" },
  { id: 25, fullName: "Logan Sargeant" },
];
dataPoints = [
  { driverId: 1, year: 2022, points: "454" },
  { driverId: 1, year: 2022, points: "308" },
  { driverId: 1, year: 2022, points: "305" },
  { driverId: 1, year: 2022, points: "275" },
  { driverId: 1, year: 2022, points: "246" },
  { driverId: 1, year: 2022, points: "240" },
  { driverId: 1, year: 2022, points: "122" },
  { driverId: 1, year: 2022, points: "92" },
  { driverId: 1, year: 2022, points: "81" },
  { driverId: 1, year: 2022, points: "49" },
  { driverId: 1, year: 2022, points: "37" },
  { driverId: 1, year: 2022, points: "37" },
  { driverId: 1, year: 2022, points: "25" },
  { driverId: 1, year: 2022, points: "23" },
  { driverId: 1, year: 2022, points: "18" },
  { driverId: 1, year: 2022, points: "12" },
  { driverId: 1, year: 2022, points: "12" },
  { driverId: 1, year: 2022, points: "6" },
  { driverId: 1, year: 2022, points: "4" },
  { driverId: 1, year: 2022, points: "2" },
  { driverId: 1, year: 2022, points: "2" },
];
point2023 = [
  { driverId: 1, year: 2023, points: "195" },
  { driverId: 3, year: 2023, points: "126" },
  { driverId: 9, year: 2023, points: "117" },
  { driverId: 6, year: 2023, points: "102" },
  { driverId: 5, year: 2023, points: "68" },
  { driverId: 4, year: 2023, points: "65" },
  { driverId: 2, year: 2023, points: "54" },
  { driverId: 15, year: 2023, points: "37" },
  { driverId: 8, year: 2023, points: "29" },
  { driverId: 23, year: 2023, points: "15" },
  { driverId: 7, year: 2023, points: "12" },
  { driverId: 19, year: 2023, points: "7" },
  { driverId: 24, year: 2023, points: "6" },
  { driverId: 22, year: 2023, points: "5" },
  { driverId: 10, year: 2023, points: "5" },
  { driverId: 18, year: 2023, points: "4" },
  { driverId: 13, year: 2023, points: "2" },
  { driverId: 21, year: 2023, points: "0" },
];
team = [
  { id: 10, fullName: "Red Bull Racing Honda RBPT" },
  { id: 11, fullName: "Mercedes" },
  { id: 12, fullName: "Aston Martin Aramco Mercedes" },
  { id: 13, fullName: "Ferrari" },
  { id: 14, fullName: "Alpine Renault" },
  { id: 15, fullName: "McLaren Mercedes" },
  { id: 16, fullName: "Alfa Romeo Ferrari" },
  { id: 17, fullName: "Haas Ferrari" },
  { id: 18, fullName: "Williams Mercedes" },
  { id: 20, fullName: "Alphatauri Honda RBPT" },
];
teamPoints = [
  { teamId: 10, year: 2023, points: "321" },
  { teamId: 11, year: 2023, points: "167" },
  { teamId: 12, year: 2023, points: "154" },
  { teamId: 13, year: 2023, points: "122" },
  { teamId: 14, year: 2023, points: "44" },
  { teamId: 15, year: 2023, points: "17" },
  { teamId: 16, year: 2023, points: "9" },
  { teamId: 17, year: 2023, points: "8" },
  { teamId: 18, year: 2023, points: "7" },
];
teamPoints = [
  { teamId: 10, year: 2022, points: "759" },
  { teamId: 13, year: 2022, points: "554" },
  { teamId: 11, year: 2022, points: "515" },
  { teamId: 14, year: 2022, points: "173" },
  { teamId: 15, year: 2022, points: "159" },
  { teamId: 16, year: 2022, points: "55" },
  { teamId: 12, year: 2022, points: "55" },
  { teamId: 17, year: 2022, points: "37" },
  { year: 2022, points: "35" },
];
race = [
  { id: 1, grandPrix: "Bahrain" },
  { id: 2, grandPrix: "Saudi Arabia" },
  { id: 3, grandPrix: "Australia" },
  { id: 4, grandPrix: "Azerbaijan" },
  { id: 5, grandPrix: "Miami" },
  { id: 6, grandPrix: "Monaco" },
  { id: 7, grandPrix: "Spain" },
  { id: 8, grandPrix: "Canada" },
];
raceData = [
  {
    year: 2023,
    raceId: 1,
    driverId: 1,
    car: "Red Bull Racing Honda RBPT",
    laps: "57",
    time: "1:33:56.736",
    point: "25",
  },
  {
    year: 2023,
    raceId: 1,
    driverId: 3,
    car: "Red Bull Racing Honda RBPT",
    laps: "57",
    time: "+11.987s",
    point: "18",
  },
  {
    year: 2023,
    raceId: 1,
    driverId: 9,
    car: "Aston Martin Aramco Mercedes",
    laps: "57",
    time: "+38.637s",
    point: "15",
  },
  {
    year: 2023,
    raceId: 1,
    driverId: 5,
    car: "Ferrari",
    laps: "57",
    time: "+48.052s",
    point: "12",
  },
  {
    year: 2023,
    raceId: 1,
    driverId: 6,
    car: "Mercedes",
    laps: "57",
    time: "+50.977s",
    point: "10",
  },
  {
    year: 2023,
    raceId: 1,
    driverId: 15,
    car: "Aston Martin Aramco Mercedes",
    laps: "57",
    time: "+54.502s",
    point: "8",
  },
  {
    year: 2023,
    raceId: 1,
    driverId: 4,
    car: "Mercedes",
    laps: "57",
    time: "+55.873s",
    point: "6",
  },
  {
    year: 2023,
    raceId: 1,
    driverId: 10,
    car: "Alfa Romeo Ferrari",
    laps: "57",
    time: "+72.647s",
    point: "4",
  },
  {
    year: 2023,
    raceId: 1,
    driverId: 23,
    car: "Alpine Renault",
    laps: "57",
    time: "+73.753s",
    point: "2",
  },
  {
    year: 2023,
    raceId: 1,
    driverId: 19,
    car: "Williams Mercedes",
    laps: "57",
    time: "+89.774s",
    point: "1",
  },
  {
    year: 2023,
    raceId: 1,
    car: "AlphaTauri Honda RBPT",
    laps: "57",
    time: "+90.870s",
    point: "0",
  },
  {
    year: 2023,
    raceId: 1,
    driverId: 25,
    car: "Williams Mercedes",
    laps: "56",
    time: "+1 lap",
    point: "0",
  },
  {
    year: 2023,
    raceId: 1,
    driverId: 13,
    car: "Haas Ferrari",
    laps: "56",
    time: "+1 lap",
    point: "0",
  },
  {
    year: 2023,
    raceId: 1,
    driverId: 21,
    car: "AlphaTauri Honda RBPT",
    laps: "56",
    time: "+1 lap",
    point: "0",
  },
  {
    year: 2023,
    raceId: 1,
    driverId: 24,
    car: "Haas Ferrari",
    laps: "56",
    time: "+1 lap",
    point: "0",
  },
  {
    year: 2023,
    raceId: 1,
    driverId: 18,
    car: "Alfa Romeo Ferrari",
    laps: "56",
    time: "+1 lap",
    point: "0",
  },
  {
    year: 2023,
    raceId: 1,
    driverId: 7,
    car: "McLaren Mercedes",
    laps: "55",
    time: "+2 laps",
    point: "0",
  },
  {
    year: 2023,
    raceId: 1,
    driverId: 8,
    car: "Alpine Renault",
    laps: "41",
    time: "DNF",
    point: "0",
  },
  {
    year: 2023,
    raceId: 1,
    driverId: 2,
    car: "Ferrari",
    laps: "39",
    time: "DNF",
    point: "0",
  },
];
raceDataForNo2 = [
  {
    year: 2023,
    raceId: 3,
    driverId: 1,
    car: "Red Bull Racing Honda RBPT",
    laps: "58",
    time: "2:32:38.371",
    points: "25",
  },
  {
    year: 2023,
    raceId: 3,
    driverId: 6,
    car: "Mercedes",
    laps: "58",
    time: "+0.179s",
    points: "18",
  },
  {
    year: 2023,
    raceId: 3,
    driverId: 9,
    car: "Aston Martin Aramco Mercedes",
    laps: "58",
    time: "+0.769s",
    points: "15",
  },
  {
    year: 2023,
    raceId: 3,
    driverId: 15,
    car: "Aston Martin Aramco Mercedes",
    laps: "58",
    time: "+3.082s",
    points: "12",
  },
  {
    year: 2023,
    raceId: 3,
    driverId: 3,
    car: "Red Bull Racing Honda RBPT",
    laps: "58",
    time: "+3.320s",
    points: "11",
  },
  {
    year: 2023,
    raceId: 3,
    driverId: 7,
    car: "McLaren Mercedes",
    laps: "58",
    time: "+3.701s",
    points: "8",
  },
  {
    year: 2023,
    raceId: 3,
    driverId: 24,
    car: "Haas Ferrari",
    laps: "58",
    time: "+4.939s",
    points: "6",
  },
  {
    year: 2023,
    raceId: 3,
    driverId: 22,
    car: "McLaren Mercedes",
    laps: "58",
    time: "+5.382s",
    points: "4",
  },
  {
    year: 2023,
    raceId: 3,
    driverId: 18,
    car: "Alfa Romeo Ferrari",
    laps: "58",
    time: "+5.713s",
    points: "2",
  },
  {
    year: 2023,
    raceId: 3,
    car: "AlphaTauri Honda RBPT",
    laps: "58",
    time: "+6.052s",
    points: "1",
  },
  {
    year: 2023,
    raceId: 3,
    driverId: 10,
    car: "Alfa Romeo Ferrari",
    laps: "58",
    time: "+6.513s",
    points: "0",
  },
  {
    year: 2023,
    raceId: 3,
    driverId: 5,
    car: "Ferrari",
    laps: "58",
    time: "+6.594s",
    points: "0",
  },
  {
    year: 2023,
    raceId: 3,
    driverId: 23,
    car: "Alpine Renault",
    laps: "56",
    time: "DNF",
    points: "0",
  },
  {
    year: 2023,
    raceId: 3,
    driverId: 8,
    car: "Alpine Renault",
    laps: "56",
    time: "DNF",
    points: "0",
  },
  {
    year: 2023,
    raceId: 3,
    driverId: 21,
    car: "AlphaTauri Honda RBPT",
    laps: "56",
    time: "DNF",
    points: "0",
  },
  {
    year: 2023,
    raceId: 3,
    driverId: 25,
    car: "Williams Mercedes",
    laps: "56",
    time: "DNF",
    points: "0",
  },
  {
    year: 2023,
    raceId: 3,
    driverId: 13,
    car: "Haas Ferrari",
    laps: "52",
    time: "DNF",
    points: "0",
  },
  {
    year: 2023,
    raceId: 3,
    driverId: 4,
    car: "Mercedes",
    laps: "17",
    time: "DNF",
    points: "0",
  },
  {
    year: 2023,
    raceId: 3,
    driverId: 19,
    car: "Williams Mercedes",
    laps: "6",
    time: "DNF",
    points: "0",
  },
];
